# Generated by Django 6.0.2 on 2026-02-06 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0003_auditsession_electricity_inflation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwp', models.FloatField(default=3.0, help_text='Puissance crête (kWc)')),
                ('orientation', models.FloatField(default=0, help_text='0=Sud, 90=Ouest, -90=Est')),
                ('tilt', models.FloatField(default=35, help_text='Inclinaison (degrés)')),
                ('hourly_production', models.JSONField(blank=True, help_text='Liste des 8760 valeurs de prod (Wh)', null=True)),
                ('hourly_consumption', models.JSONField(blank=True, help_text='Liste des 8760 valeurs de conso (Wh) - Linky ou Estimé', null=True)),
                ('total_production_kwh', models.FloatField(default=0)),
                ('total_consumption_kwh', models.FloatField(default=0)),
                ('self_consumption_rate', models.FloatField(default=0, help_text='% Autoconsommation (0-100)')),
                ('autarky_rate', models.FloatField(default=0, help_text='% Autarcie (0-100)')),
                ('surplus_kwh', models.FloatField(default=0, help_text='Surplus injecté réseau (kWh)')),
                ('missing_kwh', models.FloatField(default=0, help_text='Manque soutiré réseau (kWh)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_simulation', to='audit.auditsession')),
            ],
        ),
    ]
