# Generated by Django 6.0.2 on 2026-02-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('audit', '0004_remove_auditsession_kwh_price_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Electricity Bill'), ('QUOTE', 'Installer Quote'), ('OTHER', 'Other Document')], default='INVOICE', max_length=20)),
                ('file', models.FileField(upload_to='uploads/documents/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Analysis Pending'), ('PROCESSING', 'Processing with AI'), ('COMPLETED', 'Analysis Completed'), ('FAILED', 'Analysis Failed')], default='PENDING', max_length=20)),
                ('raw_json_result', models.JSONField(blank=True, help_text='Raw JSON output from Adobe PDF Services', null=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Structured data (e.g., kwh_price, total_amount)', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='audit.auditsession')),
            ],
        ),
    ]
