# Generated by Django 6.0.2 on 2026-02-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_documentanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsimulation',
            name='estimated_bill_reduction_eur',
            field=models.FloatField(default=0, help_text='% réduction facture'),
        ),
        migrations.AddField(
            model_name='solarsimulation',
            name='estimated_savings_eur',
            field=models.FloatField(default=0, help_text='Economies annuelles estimées (€)'),
        ),
    ]
