# Generated by Django 6.0.2 on 2026-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('admin', 'Administrateur'), ('member', 'Membre'), ('viewer', 'Visiteur')], default='member', max_length=20, verbose_name='rôle')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='poste')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'membre',
                'verbose_name_plural': 'membres',
                'ordering': ['organization', 'role', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='secteur')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employés'), ('11-50', '11-50 employés'), ('51-200', '51-200 employés'), ('201-500', '201-500 employés'), ('500+', '500+ employés')], max_length=20, verbose_name='taille entreprise')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'équipe',
                'verbose_name_plural': 'équipes',
                'ordering': ['organization', 'name'],
            },
        ),
    ]
