# Generated by Django 6.0.2 on 2026-04-02 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', 'Carte bancaire'), ('sepa_debit', 'Prélèvement SEPA'), ('paypal', 'PayPal')], max_length=20, verbose_name='type paiement')),
                ('is_default', models.BooleanField(default=False, verbose_name='défaut')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='carte derniers chiffres')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='carte marque')),
                ('card_exp_month', models.IntegerField(blank=True, null=True, verbose_name='carte expiration mois')),
                ('card_exp_year', models.IntegerField(blank=True, null=True, verbose_name='carte expiration année')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Payment Method ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'moyen paiement',
                'verbose_name_plural': 'moyens paiement',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=20, verbose_name='cycle facturation')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='fonctionnalités')),
                ('max_users', models.IntegerField(blank=True, null=True, verbose_name='utilisateurs max')),
                ('max_storage_gb', models.IntegerField(blank=True, null=True, verbose_name='stockage max GB')),
                ('api_calls_per_month', models.IntegerField(blank=True, null=True, verbose_name='appels API/mois')),
                ('trial_days', models.IntegerField(default=0, verbose_name='jours essai')),
                ('trial_requires_card', models.BooleanField(default=False, verbose_name='carte requise pour essai')),
                ('quotas', models.JSONField(blank=True, default=dict, verbose_name='quotas')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_popular', models.BooleanField(default=False, verbose_name='populaire')),
                ('display_order', models.IntegerField(default=0, verbose_name='ordre affichage')),
                ('stripe_price_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Price ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['display_order', 'price'],
                'indexes': [models.Index(fields=['slug'], name='subscriptio_slug_df9248_idx'), models.Index(fields=['is_active'], name='subscriptio_is_acti_8f27d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'En essai'), ('active', 'Actif'), ('past_due', 'En retard'), ('canceled', 'Annulé'), ('unpaid', 'Impayé'), ('incomplete', 'Incomplet')], default='trialing', max_length=20, verbose_name='statut')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='fin essai')),
                ('current_period_start', models.DateTimeField(verbose_name='début période courante')),
                ('current_period_end', models.DateTimeField(verbose_name='fin période courante')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='annuler fin période')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Customer ID')),
                ('current_usage', models.JSONField(blank=True, default=dict, verbose_name='usage actuel')),
                ('usage_reset_date', models.DateField(blank=True, null=True, verbose_name='date reset usage')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.organization', verbose_name='organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=200, unique=True, verbose_name='numéro facture')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouverte'), ('paid', 'Payée'), ('void', 'Annulée'), ('uncollectible', 'Recouvrable')], default='draft', max_length=20, verbose_name='statut')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant taxe')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('period_start', models.DateField(verbose_name='début période')),
                ('period_end', models.DateField(verbose_name='fin période')),
                ('due_date', models.DateField(verbose_name='date échéance')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payée à')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='moyen paiement')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Invoice ID')),
                ('invoice_pdf', models.FileField(blank=True, upload_to='invoices/%Y/%m/', verbose_name='PDF facture')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.organization', verbose_name='organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.subscription', verbose_name='abonnement')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='nom métrique')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prix unitaire')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='enregistré à')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.subscription', verbose_name='abonnement')),
            ],
            options={
                'verbose_name': 'enregistrement usage',
                'verbose_name_plural': 'enregistrements usage',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', '-created_at'], name='subscriptio_organiz_ec1eff_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_785d25_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_5e8870_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__12aa53_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', '-created_at'], name='subscriptio_organiz_e7cbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_9c4ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='subscriptio_status_10461a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['stripe_invoice_id'], name='subscriptio_stripe__66449d_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['subscription', '-recorded_at'], name='subscriptio_subscri_dc32c8_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['metric_name'], name='subscriptio_metric__9ff03d_idx'),
        ),
    ]
