# Generated by Django 6.0.2 on 2026-02-06 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prm_id', models.CharField(max_length=14, unique=True, verbose_name='PRM ID')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('roof_orientation', models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'North-East'), ('E', 'East'), ('SE', 'South-East'), ('S', 'South'), ('SW', 'South-West'), ('W', 'West'), ('NW', 'North-West')], max_length=2, null=True)),
                ('roof_slope', models.FloatField(blank=True, help_text='Slope in degrees', null=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linky_point', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_kwp', models.FloatField(help_text='Recommended installation size in kWp')),
                ('estimated_savings_eur', models.FloatField(help_text='Yearly savings in EUR')),
                ('self_consumption_rate', models.FloatField(help_text='Estimated self-consumption rate (0-1)')),
                ('roi_years', models.FloatField(help_text='Return on investment in years')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linky_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='energy.linkypoint')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value_kwh', models.FloatField()),
                ('data_type', models.CharField(choices=[('DAILY', 'Daily Consumption'), ('LOAD_CURVE', 'Load Curve (30min)')], default='LOAD_CURVE', max_length=20)),
                ('linky_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='energy.linkypoint')),
            ],
            options={
                'indexes': [models.Index(fields=['linky_point', 'timestamp'], name='energy_ener_linky_p_cdc834_idx')],
                'unique_together': {('linky_point', 'timestamp', 'data_type')},
            },
        ),
    ]
