# Generated by Django 6.0.2 on 2026-02-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkypoint',
            name='last_index',
            field=models.FloatField(blank=True, null=True, verbose_name='Dernier Index (kWh)'),
        ),
        migrations.AddField(
            model_name='linkypoint',
            name='subscribed_power',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Puissance Souscrite'),
        ),
        migrations.AddField(
            model_name='linkypoint',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Abonnement'),
        ),
    ]
