# Generated by Django 6.0.2 on 2026-02-06 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Audit Résidentiel', max_length=100)),
                ('subscription_price', models.DecimalField(decimal_places=2, default=15.0, help_text='Abonnement mensuel €', max_digits=6)),
                ('kwh_price_hp', models.DecimalField(decimal_places=4, default=0.2516, help_text='Prix kWh HP', max_digits=6)),
                ('kwh_price_hc', models.DecimalField(decimal_places=4, default=0.2068, help_text='Prix kWh HC', max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('kitchen', 'Cuisine'), ('living', 'Salon / Multimédia'), ('heating', 'Chauffage / Clim'), ('water', 'Eau Chaude / Sanitaire'), ('outdoor', 'Extérieur / Piscine'), ('other', 'Autre')], default='kitchen', max_length=20)),
                ('power_watts', models.IntegerField(help_text='Puissance en Watts')),
                ('qty', models.IntegerField(default=1)),
                ('hours_per_day_winter', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('hours_per_day_summer', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('is_shiftable', models.BooleanField(default=False, help_text='Peut être piloté/décalé ?')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='audit.auditsession')),
            ],
        ),
    ]
