# Generated by Django 6.0.2 on 2026-02-06 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='audit.auditsession')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('panels', 'Panneaux Photovoltaïques'), ('inverter', 'Onduleurs / Micro-onduleurs'), ('structure', "Système d'intégration / Rails"), ('elec', 'Coffrets / Câblage'), ('admin', 'Administratif (Consuel, Mairie, Etudes)'), ('logistic', 'Location Engin / Logistique'), ('labor', "Main d'œuvre / Pose"), ('battery', 'Stockage / Batteries'), ('other', 'Autre')], default='other', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('unit_price_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audit.projectquote')),
            ],
        ),
    ]
