# Generated by Django 6.0.2 on 2026-02-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_projectquote_quotelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='electricity_inflation',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Inflation élec % / an', max_digits=4),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='yearly_savings_estimated',
            field=models.DecimalField(decimal_places=2, default=1200.0, help_text='Economie annuelle estimée (€)', max_digits=10),
        ),
    ]
