# Generated by Django 6.0.2 on 2026-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditsession_electricity_inflation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditsession',
            name='kwh_price_hp',
        ),
        migrations.AddField(
            model_name='auditsession',
            name='address',
            field=models.CharField(blank=True, help_text='Adresse complète', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
