# Generated by Django 6.0.2 on 2026-04-02 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('steps', models.JSONField(default=list, verbose_name='étapes')),
                ('total_entries', models.IntegerField(default=0, verbose_name='entrées totales')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taux conversion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to='tenants.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'tunnel',
                'verbose_name_plural': 'tunnels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('report_type', models.CharField(choices=[('table', 'Table'), ('chart', 'Chart'), ('funnel', 'Funnel'), ('cohort', 'Cohort Analysis')], max_length=50, verbose_name='type rapport')),
                ('metrics', models.JSONField(default=list, verbose_name='métriques')),
                ('dimensions', models.JSONField(default=list, verbose_name='dimensions')),
                ('filters', models.JSONField(default=dict, verbose_name='filtres')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='planifié')),
                ('schedule', models.CharField(blank=True, max_length=50, verbose_name='planification')),
                ('recipients', models.JSONField(default=list, verbose_name='destinataires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tenants.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'rapport',
                'verbose_name_plural': 'rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('new_users', models.IntegerField(default=0, verbose_name='nouveaux utilisateurs')),
                ('active_users', models.IntegerField(default=0, verbose_name='utilisateurs actifs')),
                ('returning_users', models.IntegerField(default=0, verbose_name='utilisateurs récurrents')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='sessions totales')),
                ('avg_session_duration', models.IntegerField(default=0, verbose_name='durée moyenne session')),
                ('page_views', models.IntegerField(default=0, verbose_name='pages vues')),
                ('unique_page_views', models.IntegerField(default=0, verbose_name='pages vues uniques')),
                ('signups', models.IntegerField(default=0, verbose_name='inscriptions')),
                ('purchases', models.IntegerField(default=0, verbose_name='achats')),
                ('subscriptions', models.IntegerField(default=0, verbose_name='abonnements')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='revenu')),
                ('custom_metrics', models.JSONField(blank=True, default=dict, verbose_name='métriques custom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='tenants.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'statistiques quotidiennes',
                'verbose_name_plural': 'statistiques quotidiennes',
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('click', 'Click'), ('form_submit', 'Form Submit'), ('signup', 'Sign Up'), ('login', 'Login'), ('purchase', 'Purchase'), ('subscription', 'Subscription'), ('custom', 'Custom')], db_index=True, max_length=50, verbose_name="type d'événement")),
                ('event_name', models.CharField(db_index=True, max_length=200, verbose_name='nom événement')),
                ('session_id', models.CharField(db_index=True, max_length=200, verbose_name='session ID')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='propriétés')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, verbose_name='referrer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé à')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.organization', verbose_name='organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='analytics_e_organiz_8035e9_idx'), models.Index(fields=['organization', 'event_type'], name='analytics_e_organiz_db98cc_idx'), models.Index(fields=['organization', 'user', '-created_at'], name='analytics_e_organiz_e16727_idx'), models.Index(fields=['session_id'], name='analytics_e_session_83836a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=200, verbose_name='nom métrique')),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('summary', 'Summary')], max_length=50, verbose_name='type métrique')),
                ('value', models.JSONField(default=dict, verbose_name='valeur')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('hour', models.IntegerField(blank=True, null=True, verbose_name='heure')),
                ('dimensions', models.JSONField(blank=True, default=dict, verbose_name='dimensions')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tenants.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'métrique',
                'verbose_name_plural': 'métriques',
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['organization', 'date'], name='analytics_m_organiz_63e22e_idx'), models.Index(fields=['organization', 'metric_name', '-date'], name='analytics_m_organiz_b15d13_idx')],
                'unique_together': {('organization', 'metric_name', 'date', 'hour')},
            },
        ),
    ]
