# Generated by Django 6.0.2 on 2026-04-02 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('system', 'Système')], default='info', max_length=20, verbose_name='type notification')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='données')),
                ('action_url', models.URLField(blank=True, verbose_name='URL action')),
                ('action_label', models.CharField(blank=True, max_length=100, verbose_name='label action')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu à')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé à')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expire à')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.organization', verbose_name='organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('inapp', 'In-App')], max_length=20, verbose_name='canal')),
                ('recipient', models.CharField(max_length=200, verbose_name='destinataire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Délivré'), ('failed', 'Échoué'), ('bounced', 'Rejeté')], default='pending', max_length=20, verbose_name='statut')),
                ('provider_message_id', models.CharField(blank=True, max_length=200, verbose_name='ID message provider')),
                ('error_message', models.TextField(blank=True, verbose_name='message erreur')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé à')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='délivré à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'log notification',
                'verbose_name_plural': 'logs notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='notifications email activées')),
                ('email_on_signup', models.BooleanField(default=True, verbose_name='email à inscription')),
                ('email_on_purchase', models.BooleanField(default=True, verbose_name='email à achat')),
                ('email_on_subscription', models.BooleanField(default=True, verbose_name='email à abonnement')),
                ('email_marketing', models.BooleanField(default=False, verbose_name='email marketing')),
                ('push_notifications_enabled', models.BooleanField(default=True, verbose_name='notifications push activées')),
                ('sms_notifications_enabled', models.BooleanField(default=False, verbose_name='notifications SMS activées')),
                ('sms_on_purchase', models.BooleanField(default=False, verbose_name='SMS à achat')),
                ('sms_on_subscription', models.BooleanField(default=False, verbose_name='SMS à abonnement')),
                ('inapp_notifications_enabled', models.BooleanField(default=True, verbose_name='notifications in-app activées')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immédiat'), ('hourly', 'Horaire'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('never', 'Jamais')], default='immediate', max_length=20, verbose_name='fréquence digest')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='heures calme activées')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='début heures calme')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='fin heures calme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'préférence notification',
                'verbose_name_plural': 'préférences notifications',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=100, verbose_name='clé template')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('html_content', models.TextField(verbose_name='contenu HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='contenu texte')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='tenants.organization', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'template email',
                'verbose_name_plural': 'templates emails',
                'ordering': ['organization', 'template_key'],
                'unique_together': {('organization', 'template_key')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', '-created_at'], name='notificatio_is_read_1cb71a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', '-created_at'], name='notificatio_organiz_f822ba_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification'], name='notificatio_notific_ca68c9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel'], name='notificatio_channel_e46ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='notificatio_status_a242db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user',)},
        ),
    ]
